### PR TITLE
Backport known CVEs to 8.6.0

### PR DESCRIPTION
**Pull request by tescande**
This change backports CVEs 2024-2004, 2024-2379, 2024-2398, 2024-2466, 2024-6197, and 2024-7264.

### CODE REVIEW

**Review by gduperrey — APPROVED** [review]

**Comment by stormi** [comment]
Did all patches apply cleanly? If yes, this could be an interesting piece of information in the commit message. Else, we try to explain our backport-related changes in patch headers.

**Comment by stormi** [comment]
No @bleader in reviewers?

**Review by stormi — APPROVED** [review]

**Comment by bleader** [comment]
> Did all patches apply cleanly? If yes, this could be an interesting piece of information in the commit message. Else, we try to explain our backport-related changes in patch headers.

What I generally do is:
- keep the title of the patch
- add a `Backport note:` at the start of the commit log, stating how it was applied (git, patch, manual application…), if it was not applied without messages or manual changes, specify if there were offsets, fuzz, or manual changes
- add a `Backported-by: Name FirstName <mail>` at the end of the `Signed-off-by:` section

**Review by bleader — APPROVED** [review]
`XCP-ng notes:` section in the patches that have changes should be enough this time, I need to write some documentation about that :)

**Review by ydirson — APPROVED** [review]
no surface objection

**Comment by tescande** [comment]
Koji build: [v8.3-incoming](https://koji.xcp-ng.org/taskinfo?taskID=62553)

**Pull request merged**
